name: typing_text_animation
description: "This package creates a Typing Text Animation"
version: 0.1.0
homepage: "https://github.com/Sandeepsunil01/typing-text-animation"

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.typing_text_animation
        pluginClass: TypingTextAnimationPlugin
      ios:
        pluginClass: TypingTextAnimationPlugin
      linux:
        pluginClass: TypingTextAnimationPlugin
      macos:
        pluginClass: TypingTextAnimationPlugin
      windows:
        pluginClass: TypingTextAnimationPluginCApi
      web:
        pluginClass: TypingTextAnimationWeb
        fileName: typing_text_animation_web.dart
